steps:
  # Dockerイメージをビルド（環境変数を設定）
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/bybitbot-frontend:latest'
      - '--build-arg'
      - 'REACT_APP_API_URL=https://bybitbot-backend-731283498892.asia-northeast1.run.app'
      - '.'
    dir: '.'

  # イメージをプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bybitbot-frontend:latest']

# ビルドされたイメージ
images:
  - 'gcr.io/$PROJECT_ID/bybitbot-frontend:latest'